# Generated by Django 5.0.2 on 2024-04-12 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kittenfactory', '0005_remove_payment_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
