# Generated by Django 5.0.2 on 2024-04-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kittenfactory', '0009_auto_20240412_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(),
        ),
    ]
