# Generated by Django 5.0.2 on 2024-04-13 21:58

from django.db import migrations
from django.contrib.auth.models import User
def create_default_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    if not User.objects.filter(username='defaultuser').exists():
        User.objects.create_user(username='defaultuser', password='defaultpassword')
class Migration(migrations.Migration):

    dependencies = [
        ('kittenfactory', '0011_alter_order_date_alter_order_product_and_more'),
    ]

    operations = [ migrations.RunPython(create_default_user),
    ]
