# Generated by Django 5.0.2 on 2024-04-13 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kittenfactory', '0012_auto_20240413_1558'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(default= 0 , on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(default='default', on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pmt_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('credit_card', models.CharField(max_length=19)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kittenfactory.customer')),
            ],
        ),
    ]
